### PR TITLE
Added explicit CodePagesEncodingProvider to add .net core compatibility

### PR DESCRIPTION
**Pull request by mlof**

### CODE REVIEW

**Comment by marceldev89** [comment]
Thank you. Is the library broken without this change?

**Comment by tym32167** [comment]
Why do 3 party library should care about client stuff like encoding? Lets client to decide how to handle encoding issues. Battlenet - made as Standard 2.0 library and it can be used not only with Asp.NET core 2. Moreover, setting encoding in BattleyeClient class? This is not a purpose to do things like that. If you have asp.net core app - please, setup encoding inside Startup class and dont mix this with Battleye code.   Voting to reject this PR and close.

**Comment by Vipeax** [comment]
I agree with @tym32167.

**Comment by marceldev89** [comment]
I keep mistaking the differences between all the .NET versions these days.. Haven't been in the .NET realm for a while now and assumed it _might_ have broken something somewhere. But I agree, this is probably not a job for the library. Thanks for the effort though :heart:

https://github.com/marceldev89/BattleNET/pull/47#issuecomment-467061459
> I agree with @tym32167.
He's alive! :smiley:

**Pull request closed without merging**
